version: '3'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - POSTGRES_HOST=your_postgres_host
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_USER=your_postgres_user
  #     - POSTGRES_PASSWORD=your_postgres_password
  #     - POSTGRES_DB=your_postgres_database
  #   depends_on:
  #     - postgres

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: your_postgres_user
  #     POSTGRES_PASSWORD: your_postgres_password
  #     POSTGRES_DB: your_postgres_database
  #   ports:
  #     - "5432:5432"
